### ISSUE TITLE
Correct a type error in OptinProvider

### ISSUE THREAD

**Issue by wbuacct** [wherebyus/general-tasks#787]
## Reproduction Steps
This error:
```
PHP Fatal error: Uncaught TypeError: Argument 1 passed to WBU\\Providers\\WordPressProvider::isPostEditor() must be of the type string, null given, called in /nas/content/live/wbudevelop/wp-content/plugins/wherebyapp/app/Providers/OptinProvider.php on line 127 and defined in /nas/content/live/wbudevelop/wp-content/plugins/wherebyapp/app/Providers/WordPressProvider.php:303
Stack trace:
#0 /nas/content/live/wbudevelop/wp-content/plugins/wherebyapp/app/Providers/OptinProvider.php(127): WBU\\Providers\\WordPressProvider->isPostEditor(NULL)
#1 [internal function]: WBU\\Providers\\OptinProvider->enqueueOptinScriptsInEditor(NULL)
#2 /nas/content/live/wbudevelop/wp-includes/class-wp-hook.php(286): call_user_func_array(Array, Array)
#3 /nas/content/live/wbudevelop/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#4 /nas/content/live/wbudevelop/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#5 /nas/content/live/wbudevelop/wp-admin/includes/template.php(1796): do_action('admin_enqueue_s...', NULL)
#6 /nas/conten in /nas/content/live/wbudevelop/wp-content/plugins/wherebyapp/app/Providers/WordPressProvider.php on line 303, referer: https://miami.wbudevelop.wpengine.com/wp-admin/post.php?post=107864&action=edit
```

### Additional information:
 - BTID-397
 - [Link to Airtable](https://airtable.com/tblWM0skJCYIBSL6c/viwVfilkH4LzzRsKs/rec3ZUpMQWQ3pGYLJ) - (may include image attachments)

### Submitted by
Name: Michael Schofield 
Email: michael@whereby.us
Slack ID: michael

**Comment by michaelschofield** [comment]
## QA
1. Create or update an optin, and ensure that everything looks in order.
