### ISSUE TITLE
Call to a member function get_product() on array

### ISSUE THREAD

**Issue by ErnieAtLYD** [wherebyus/general-tasks#937]
```
Call to a member function get_product() on array in /nas/content/live/wbu/wp-content/themes/thenewtropic/woocommerce/emails/email-order-items.php:27 Stack trace: 
#0 /nas/content/live/wbu/wp-content/plugins/woocommerce/includes/wc-core-functions.php(203): include() 
#1 /nas/content/live/wbu/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-order.php(2062): wc_get_template('emails/email-or...', Array) 
#2 /nas/content/live/wbu/wp-content/themes/thenewtropic/woocommerce/emails/email-order-details.php(45): WC_Abstract_Order->email_order_items_table(Array) 
#3 /nas/content/live/wbu/wp-content/plugins/woocommerce/includes/wc-core-functions.php(203): include('/nas/content/li...') 
#4 /nas/content/live/wbu/wp-content/plugins/woocommerce-subscriptions/includes/class-wc-subscriptions-email.php(303): wc_get_template('emails/email-or...', Array, '', '/nas/content/li...') 
#5 [internal function]: WC_Subscriptions_Email::order_details(Object(WC_Order), false, false, Object(WCS_Email_Customer_Payment_ in /nas/content/live/wbu/wp-content/themes/thenewtropic/woocommerce/emails/email-order-items.php on line 27
```

**Comment by ErnieAtLYD** [comment]
Manually removed `/themes/thenewtropic/woocommerce/emails/email-order-details.php` from production via SFTP as the code isn't in frodo and defaults to what's inside the woocommerce plugin.
