### ISSUE TITLE
Uncaught Error: Call to a member function getUniqueId() on null

### ISSUE THREAD

**Issue by ErnieAtLYD** [wherebyus/general-tasks#944]
```
unexpected shutdown: PHP Fatal error Uncaught Error: Call to a member function getUniqueId() on null in /nas/content/live/wbu/wp-content/plugins/wherebyapp/app/Http/Controllers/ReferralController.php:539 Stack trace: 
#0 [internal function]: WBUHttpControllersReferralController->updateUsersReferralCount(125955) 
#1 /nas/content/live/wbu/wp-includes/class-wp-hook.php(286): call_user_func_array(Array, Array) 
#2 /nas/content/live/wbu/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array) 
#3 /nas/content/live/wbu/wp-includes/plugin.php(515): WP_Hook->do_action(Array) 
#4 /nas/content/live/wbu/wp-content/plugins/wherebyapp/vendor/prospress/action-scheduler/classes/ActionScheduler_Action.php(22): do_action_ref_array('wherebyEventRef...', Array) 
#5 /nas/content/live/wbu/wp-content/plugins/wherebyapp/vendor/prospress/action-scheduler/classes/ActionScheduler_Abstract_QueueRunner.php(59): ActionScheduler_Action->execute() 
#6 /nas/content/live/wbu/wp-content/plugins/wherebyapp/vendor/prospress/action-scheduler/classes/ActionScheduler_QueueRu in /nas/content/live/wbu/wp-content/plugins/wherebyapp/app/Http/Controllers/ReferralController.php on line 539
```

**Comment by carogea** [comment]
Related to people getting credit for referrals

**Comment by ErnieAtLYD** [comment]
Line 539 no longer exists so I'm closing until another bug report pops up.
