### ISSUE TITLE
Call to a member function getUniqueId() on null

### ISSUE THREAD

**Issue by ErnieAtLYD** [wherebyus/general-tasks#965]
```
[Mon Mar 18 11:40:18.514809 2019] [php7:error] [pid 13404] [client 127.0.0.1:18664] PHP Fatal error: Uncaught Error: Call to a member function getUniqueId() on null in /nas/content/live/wbu/wp-content/plugins/wherebyapp/app/Http/Controllers/ReferralController.php:539
Stack trace:
#0 [internal function]: WBU\\Http\\Controllers\\ReferralController->updateUsersReferralCount(22331)
#1 /nas/content/live/wbu/wp-includes/class-wp-hook.php(286): call_user_func_array(Array, Array)
#2 /nas/content/live/wbu/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#3 /nas/content/live/wbu/wp-includes/plugin.php(515): WP_Hook->do_action(Array)
#4 /nas/content/live/wbu/wp-content/plugins/wherebyapp/vendor/prospress/action-scheduler/classes/ActionScheduler_Action.php(22): do_action_ref_array('wherebyEventRef...', Array)
#5 /nas/content/live/wbu/wp-content/plugins/wherebyapp/vendor/prospress/action-scheduler/classes/ActionScheduler_Abstract_QueueRunner.php(59): ActionScheduler_Action->execute()
#6 /nas/content/live/wbu/wp-content/plugins/wherebyapp/vendor/prospress/action-scheduler/classes/ActionScheduler_QueueRun in /nas/content/live/wbu/wp-content/plugins/wherebyapp/app/Http/Controllers/ReferralController.php on line 539
```

Note: Will help give Kristem back some time

**Comment by michaelschofield** [comment]
## QA
1. Nothing really to QA. Go team : ).
